[package]
name = "nyah"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.5.3"
blake2 = "0.10"
hex = "0.4.3"
local-ip-address = "0.4"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"